<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\..\src\ThrottleWatch.Client\ThrottleWatch.Client.csproj" />
    <ProjectReference Include="..\..\src\ThrottleWatch.Dashboard\ThrottleWatch.Dashboard.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <RootNamespace>ThrottleWatch.Samples.WebApiWithPolicies</RootNamespace>
  </PropertyGroup>

</Project>
